### ISSUE TITLE
ERROR: hyperopt.exceptions.AllTrialsFailed

### ISSUE THREAD

**Issue by suyashjain0** [RasaHQ/nlu-hyperopt#12]
files

space.py 

```
from hyperopt import hp
search_space = {
    "epochs": hp.qloguniform("epochs", 0, 4, 2),
    'max_df': hp.uniform('max_df', 1, 2),
    'max_ngrams': hp.quniform('max_ngram', 3, 9, 1)
    }
```

template_config.yml

```
language: en
pipeline:
- name: "WhitespaceTokenizer"
- name: "CountVectorsFeaturizer"
  analyzer: char_wb
  max_df: {max_df}
  min_ngram: 1
  max_ngram: {max_ngrams} 
- name: "DIETClassifier"
  epochs: {epochs}
- name: "ResponseSelector"
  epochs: 200
- name: RegexFeaturizer
- name: EntitySynonymMapper
```

While running cmd : python -m nlu_hyperopt.app

**below are logs :**

```
INFO:__main__:Starting up
Running experiment : default
Max evaluations: 10
Search space: {'epochs': <hyperopt.pyll.base.Apply object at 0x7fa132860590>, 'max_df': <hyperopt.pyll.base.Apply object at 0x7fa132860710>, 'max_ngrams': <hyperopt.pyll.base.Apply object at 0x7fa1328608d0>}
  0%|                                                                                                       | 0/10 [00:00<?, ?trial/s, best loss=?]INFO:hyperopt.tpe:build_posterior_wrapper took 0.001336 seconds
INFO:hyperopt.tpe:TPE using 0 trials
INFO:rasa.nlu.model:Starting to train component WhitespaceTokenizer
INFO:rasa.nlu.model:Finished training component.
INFO:rasa.nlu.model:Starting to train component CountVectorsFeaturizer
ERROR:nlu_hyperopt.optimization:'float' object cannot be interpreted as an integer
..
..
...
..
ERROR:nlu_hyperopt.optimization:'float' object cannot be interpreted as an integer
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:07<00:00,  1.38trial/s, best loss: 1]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/abc/Documents/ds/webiner session/rasa-workshops/sample_code/nlu-hyperopt/nlu_hyperopt/app.py", line 67, in <module>
    max_evals=max_evals)
  File "/Users/abc/Envs/tenv/lib/python3.7/site-packages/hyperopt/fmin.py", line 516, in fmin
    return trials.argmin
  File "/Users/abc/Envs/tenv/lib/python3.7/site-packages/hyperopt/base.py", line 622, in argmin
    best_trial = self.best_trial
  File "/Users/abc/Envs/tenv/lib/python3.7/site-packages/hyperopt/base.py", line 613, in best_trial
    raise AllTrialsFailed
**hyperopt.exceptions.AllTrialsFailed**
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @desmarchris will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by desmarchris** [comment]
@suyashjain0 thanks for the post. I'm able to reproduce this locally and think the issue is around setting `max_ngram` as a variable to test, because it works when you set that to a specific number. Tagging in @melindaloubser1 to review when she has some time!

**Comment by suyashjain0** [comment]
Okay thanks, please update with the solution to error for max_ngrams

**Comment by melindaloubser1** [comment]
The problem seems to be  that `hp.quniform('max_ngram', 3, 9, 1)` returns a search space of floating point numbers, not integers, which is required for max_ngrams. This was an issue in hyperopt before: https://github.com/hyperopt/hyperopt/issues/253

but that issue was fixed in a much earlier release. I'm checking to see why it might have come back, in the meantime see some workarounds  on this thread: https://github.com/hyperopt/hyperopt/issues/253

**Comment by melindaloubser1** [comment]
Ok, I see the problem did in fact come back in a later version of hyperopt and hasn't been fixed again:
https://github.com/hyperopt/hyperopt/issues/508

As described there, a functional workaround is to cast to int e.g.

```
from hyperopt.pyll.base import scope
from hyperopt import hp

search_space = {
    "epochs": hp.qloguniform("epochs", 0, 4, 2),
    'max_df': hp.uniform('max_df', 1, 2),
    'max_ngrams': scope.int(hp.quniform('max_ngram', 3, 9, 1))
    }
```

I'll open a PR to fix the examples.
