### ISSUE TITLE
ERROR:nlu_hyperopt.optimization:no display name

### ISSUE THREAD

**Issue by Growing-bison** [RasaHQ/nlu-hyperopt#7]
Hi 
Thanks for your share project.
When i run the demo, the error listed as follow:

`
ERROR:nlu_hyperopt.optimization:no display name and no $DISPLAY environment variable
Traceback (most recent call last):
  File "/home/miniconda3/envs/py36/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
AttributeError: 'list' object has no attribute 'argmin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/miniconda3/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/miniconda3/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/myapp/practise_demo/nlu-hyperopt/nlu_hyperopt/app.py", line 49, in <module>
    max_evals=max_evals)
  File "/home/miniconda3/envs/py36/lib/python3.6/site-packages/hyperopt/fmin.py", line 387, in fmin
    return trials.argmin
  File "/home/miniconda3/envs/py36/lib/python3.6/site-packages/hyperopt/base.py", line 590, in argmin
    best_trial = self.best_trial
  File "/home/miniconda3/envs/py36/lib/python3.6/site-packages/hyperopt/base.py", line 585, in best_trial
    best = np.argmin(losses)
  File "/home/miniconda3/envs/py36/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1172, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)
  File "/home/miniconda3/envs/py36/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/miniconda3/envs/py36/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence

`

ubuntu 18.04
python 3.6.8
rasa-nlu 0.13.8
numpy 1.16.1
hyperopt 0.1.1
flask 1.0.2

Command: **python -m nlu_hyperopt.app**

**Comment by augusto-peterlevitz** [comment]
I think it must be the Rasa NLU version. I was trying to use the 13.1 version and I was getting the same error. Then I installed the 15.0 version and this error did not occured. 
But I still want to do the hipperparameter optimization on the previous version.

**Comment by Growing-bison** [comment]
Thx. Having not chance to adjust it again recently, i am so sorry for that. My model is also being excuated in newer version. I will try on your tips later.

**Comment by indam23** [comment]
Closing as stale / resolved
